In [9]:
# brew install tesseract-lang
from img2table.ocr import TesseractOCR
from img2table.document import Image


# Instantiation of OCR
# ocr = TesseractOCR(n_threads=6)

# read image
src = './lesfmip_papertable.jpeg'
image = Image(src, detect_rotation=False)

In [14]:
extracted = image.extract_tables(
                                      implicit_rows=False,
                                      borderless_tables=True,
                                      min_confidence=50)

In [15]:
extracted

[ExtractedTable(title=None, bbox=(273, 536, 1085, 1208),shape=(21, 5)),
 ExtractedTable(title=None, bbox=(273, 2, 1085, 557),shape=(18, 5))]

In [16]:
extracted[0]

ExtractedTable(title=None, bbox=(273, 536, 1085, 1208),shape=(21, 5))

In [18]:
ocr = TesseractOCR(n_threads=1, 
                   lang="eng", 
                   psm=11)

tesseract 5.3.1
 leptonica-1.82.0
  libgif 5.2.1 : libjpeg 8d (libjpeg-turbo 2.1.4) : libpng 1.6.39 : libtiff 4.4.0 : zlib 1.2.11 : libwebp 1.3.0 : libopenjp2 2.5.0
 Found NEON
 Found libarchive 3.6.2 zlib/1.2.11 liblzma/5.4.1 bz2lib/1.0.8 liblz4/1.9.4 libzstd/1.5.4
 Found libcurl/7.87.0 SecureTransport (LibreSSL/3.3.6) zlib/1.2.11 nghttp2/1.51.0

OSError: Tesseract 'eng' trainned data cannot be located

In [19]:
help(extracted[0])

Help on ExtractedTable in module img2table.tables.objects.extraction object:

class ExtractedTable(builtins.object)
 |  ExtractedTable(bbox: img2table.tables.objects.extraction.BBox, title: Optional[str], content: OrderedDict[int, List[img2table.tables.objects.extraction.TableCell]]) -> None
 |
 |  ExtractedTable(bbox: img2table.tables.objects.extraction.BBox, title: Optional[str], content: OrderedDict[int, List[img2table.tables.objects.extraction.TableCell]])
 |
 |  Methods defined here:
 |
 |  __eq__(self, other)
 |      Return self==value.
 |
 |  __init__(self, bbox: img2table.tables.objects.extraction.BBox, title: Optional[str], content: OrderedDict[int, List[img2table.tables.objects.extraction.TableCell]]) -> None
 |      Initialize self.  See help(type(self)) for accurate signature.
 |
 |  __repr__(self)
 |      Return repr(self).
 |
 |  html_repr(self, title: Optional[str] = None) -> str
 |      Create HTML representation of the table
 |      :param title: title of HTML paragraph
 |      :return: HTML string
 |
 |  ----------------------------------------------------------------------
 |  Readonly properties defined here:
 |
 |  df
 |      Create pandas DataFrame representation of the table
 |      :return: pandas DataFrame containing table data
 |
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |
 |  __dict__
 |      dictionary for instance variables (if defined)
 |
 |  __weakref__
 |      list of weak references to the object (if defined)
 |
 |  ----------------------------------------------------------------------
 |  Data and other attributes defined here:
 |
 |  __annotations__ = {'bbox': <class 'img2table.tables.objects.extraction...
 |
 |  __dataclass_fields__ = {'bbox': Field(name='bbox',type=<class 'img2tab...
 |
 |  __dataclass_params__ = _DataclassParams(init=True,repr=True,eq=True,or...
 |
 |  __hash__ = None
 |
 |  __match_args__ = ('bbox', 'title', 'content')

In [20]:
a = extracted[0]

In [21]:
a.df

       0     1     2     3     4
0   None  None  None  None  None
1   None  None  None  None  None
2   None  None  None  None  None
3   None  None  None  None  None
4   None  None  None  None  None
5   None  None  None  None  None
6   None  None  None  None  None
7   None  None  None  None  None
8   None  None  None  None  None
9   None  None  None  None  None
10  None  None  None  None  None
11  None  None  None  None  None
12  None  None  None  None  None
13  None  None  None  None  None
14  None  None  None  None  None
15  None  None  None  None  None
16  None  None  None  None  None
17  None  None  None  None  None
18  None  None  None  None  None
19  None  None  None  None  None
20  None  None  None  None  None